# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u540d')),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u59d3')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
