# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0002_mlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlogin',
            name='password',
            field=models.CharField(default=123, max_length=21, verbose_name='\u5bc6\u7801'),
            preserve_default=False,
        ),
    ]
