# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0004_messagepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessagePost',
        ),
    ]
