# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0006_auto_20160526_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlogin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mlogin',
            name='last_name',
        ),
        migrations.AddField(
            model_name='mlogin',
            name='name',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='\u540d'),
        ),
    ]
