# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0008_auto_20160526_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
