# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0009_firstmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
