# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0010_auto_20160528_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
