# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken', '0011_secondmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstrestaurant',
            name='introduction',
            field=models.TextField(default='\u9c81\u5927\u7b2c\u4e00\u9910\u5385\u7ecf\u5178\u7f8e\u98df\uff01'),
        ),
        migrations.AddField(
            model_name='secondrestaurant',
            name='introduction',
            field=models.TextField(default='\u9c81\u5927\u7b2c\u4e00\u9910\u5385\u7ecf\u5178\u7f8e\u98df\uff01'),
        ),
    ]
