# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untitled', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagepost',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='messagepost',
            name='last_name',
        ),
        migrations.AddField(
            model_name='messagepost',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='\u540d\u5b57'),
        ),
    ]
