# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untitled', '0002_auto_20160524_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagepost',
            options={'ordering': ['updated']},
        ),
    ]
